# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4bcf9284f353a6345433c190958e9ecd6587832839f92ba2f0229794a1ad0a7fff9c9668dd0dccb9bc80687b442b7138833347758f8cb40387e7f59db5055ea

test:
  secret_key_base: 93bbb53f0c58301328948f5a8b803237a502d1c6775c2a1e0cdcb4abc34cb6f6b751c7bc3657d11f3f8b8e454c55c97c0fa5953e9ee2a4a2e91428fcb88e16ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
